SELECT
    Scores.UserID
    ,SUM(Scores.Score) AS TotalScore
    ,U.Name AS UserName
FROM
    (
    -- Retrieve total score generated by Accepted Answers
    SELECT
        VTCA.AnsweredBy_UserID AS UserID
        ,COUNT(AnsweredBy_UserID) * 10 AS Score
    FROM gdn_v_topcontributors_answers VTCA
    WHERE
        (VTCA.AcceptanceDateTime >= DATE('2012-03-01')) AND 
        (VTCA.AcceptanceDateTime < DATE('2012-03-31'))
    GROUP BY
        VTCA.AnsweredBy_UserID

    UNION ALL

    -- Retrieve total score generated by Thanks
    SELECT
        VTCT.ThanksTo_UserID AS UserID
        ,COUNT(ThanksTo_UserID) * 2 AS Score
    FROM gdn_v_topcontributors_thanks VTCT
    WHERE
        (VTCT.ThanksDateTime >= DATE('2012-03-01')) AND 
        (VTCT.ThanksDateTime < DATE('2012-03-31'))
    GROUP BY
        VTCT.ThanksTo_UserID
    ) AS Scores
    JOIN
    gdn_user U ON
        (U.UserID = Scores.UserID)
GROUP BY Scores.UserID
ORDER BY TotalScore DESC
LIMIT 10