SELECT
    U.UserID
    ,U.Name AS UserName
    ,COALESCE(AnswersScores.TotalAcceptedAnswers, 0) AS TotalAcceptedAnswers
    ,COALESCE(ThanksScores.TotalThanks, 0) AS TotalThanks
    ,(COALESCE(AnswersScores.TotalAcceptedAnswers, 0) * 10) + (COALESCE(ThanksScores.TotalThanks, 0) * 1) AS TotalScore
FROM
    gdn_user U
    LEFT JOIN
    (
    -- Retrieve total score generated by Accepted Answers
    SELECT
        VTCA.AnsweredBy_UserID AS UserID
        ,COUNT(AnsweredBy_UserID) AS TotalAcceptedAnswers
    FROM gdn_v_topcontributors_answers VTCA
    WHERE
        (VTCA.AcceptanceDateTime >= DATE('2012-03-01')) AND 
        (VTCA.AcceptanceDateTime < DATE('2012-04-01'))
    GROUP BY
        VTCA.AnsweredBy_UserID
    ) AS AnswersScores ON
        (AnswersScores.UserID = U.UserID)
    LEFT JOIN
    (
    -- Retrieve total score generated by Thanks
    SELECT
        VTCT.ThanksTo_UserID AS UserID
        ,COUNT(ThanksTo_UserID) AS TotalThanks
    FROM gdn_v_topcontributors_thanks VTCT
    WHERE
        (VTCT.ThanksDateTime >= DATE('2012-03-01')) AND 
        (VTCT.ThanksDateTime < DATE('2012-04-01'))
    GROUP BY
        VTCT.ThanksTo_UserID
    ) AS ThanksScores ON
        (ThanksScores.UserID = U.UserID)
HAVING
    (TotalAcceptedAnswers IS NOT NULL) OR
    (TotalThanks IS NOT NULL)
ORDER BY TotalScore DESC
LIMIT 10